### ISSUE TITLE
war attacks

### ISSUE THREAD

**Issue by Westo48** [Westo48/clash-discord#311]
# command name

war attacks

## description

currently war attacks is an option for war stars, just split that up into 2 commands

## command overview

- options
    - clan role
    - cwl war selection

## tasks
- [ ] discord responder function
- [ ] cog command addition
- [ ] readme documentation

**Comment by GustavoSchip** [comment]
Is this already implemented?
If not I am willing to help this amazing bot!

**Comment by Westo48** [comment]
@GustavoSchip it has not, you are absolutely more than welcome to help! Really all the plan was is to split up the "/war stars" command options into 2 separate commands.

**Comment by GustavoSchip** [comment]
> @GustavoSchip it has not, you are absolutely more than welcome to help! Really all the plan was is to split up the "/war stars" command options into 2 separate commands.

Seems simple enough (Famous last words)

**Comment by Westo48** [comment]
closing as correcting in new project
