### ISSUE TITLE
ClashFrame CWLWar notInWar None response

### ISSUE THREAD

**Issue by Westo48** [Westo48/clash-discord#46]
update ClashFrame CWLWar notInWar response to None

**Comment by Westo48** [comment]
https://github.com/Westo48/clash-discord/blob/0073ee5365d3b521386d568edc63ce0b6a59c862/CWLWar.py#L113

**Comment by DannyMoses** [comment]
Hello, I'd like to take a crack at working on this issue. Is the intended behavior for CWLWar to return None rather than a CWLWar object? Also is there any other part of the project that will need to be changed to work with that change?

**Comment by Westo48** [comment]
> Hello, I'd like to take a crack at working on this issue. Is the intended behavior for CWLWar to return None rather than a CWLWar object? Also is there any other part of the project that will need to be changed to work with that change?

That sounds great! If I'm being transparent I haven't had a contributor before, so this is very new to me! However I would absolutely love to see how this works!

This should be a one line fix, and you are correct in your assumption, returning None rather than the object is the intention. There shouldn't be anything else that should be changed, however I will confirm that prior to merging the pull request.

**Comment by DannyMoses** [comment]
> 
> 
> > Hello, I'd like to take a crack at working on this issue. Is the intended behavior for CWLWar to return None rather than a CWLWar object? Also is there any other part of the project that will need to be changed to work with that change?
> 
> That sounds great! If I'm being transparent I haven't had a contributor before, so this is very new to me! However I would absolutely love to see how this works!
> 
> This should be a one line fix, and you are correct in your assumption, returning None rather than the object is the intention. There shouldn't be anything else that should be changed, however I will confirm that prior to merging the pull request.

Thanks! This is my first time contributing to a project so I just wanted to make sure I understood everything correctly.

**Comment by Westo48** [comment]
> > 
> 
> > 
> 
> > > Hello, I'd like to take a crack at working on this issue. Is the intended behavior for CWLWar to return None rather than a CWLWar object? Also is there any other part of the project that will need to be changed to work with that change?
> 
> > 
> 
> > That sounds great! If I'm being transparent I haven't had a contributor before, so this is very new to me! However I would absolutely love to see how this works!
> 
> > 
> 
> > This should be a one line fix, and you are correct in your assumption, returning None rather than the object is the intention. There shouldn't be anything else that should be changed, however I will confirm that prior to merging the pull request.
> 
> 
> 
> Thanks! This is my first time contributing to a project so I just wanted to make sure I understood everything correctly.
> 
> 

Sounds like it will be a learning experience for both of us then 😃! If you have any questions please feel free to email me, email is in my [portfolio](https://westo48.github.io/Portfolio/).
