### ISSUE TITLE
detect removal events and delete from database accordingly

### ISSUE THREAD

**Issue by Westo48** [Westo48/clash-discord#48]
detect when roles and guilds are removed and delete from database accordingly

**Comment by Westo48** [comment]
[guild role delete event doc](https://discordpy.readthedocs.io/en/stable/api.html?highlight=role#discord.on_guild_role_delete)

[guild delete event doc](https://discordpy.readthedocs.io/en/stable/api.html?highlight=on_guild#discord.on_guild_remove)

**Comment by DannyMoses** [comment]
I can give this a shot if that's alright.

**Comment by Westo48** [comment]
That would be really cool!! Certainly let me know if you have any questions. I have included the documentation for the events as well as the role deletion.

**Comment by Westo48** [comment]
if the guild has claimed a bot_channel, then send the role database deletion response to that bot_channel _if bot channel is found in role.guild discord response_

get ctx same as 

bot_channel is currently returned, but crud operations for guild.bot_channel are not set up. Shouldn't affect business logic, but won't be able to be tested

**Comment by DannyMoses** [comment]
Sounds good. Catching the events seems easy enough so far.
